### ISSUE TITLE
progressbar bij uploaden groot bestand

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#1]
Een progressbar of andere voortgangsindicator bij uploaden van grote bestanden of trage verbindingen zou goed zijn.

**Comment by coret** [comment]
doorgevoerd https://github.com/netwerk-digitaal-erfgoed/mi2rdf/commit/d78c2338a1dbf2ddf065ca8b425e573301fa4993
