### ISSUE TITLE
formaat detecteren txt of xml

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#16]
De Export XML bestanden vanuit Mais Flexis worden opgeslagen als `.txt` met `_flexis` in de bestandsnaam bijv `BEELDBANK_FOT_DOC_5_14_39_flexis.txt`. Zou je ipv op de extensie, op `_flexis` kunnen matchen om MF-Export-XML-to-JSON te starten?

**Comment by coret** [comment]
We gebruiken MF-Export-XML-to-JSON niet meer.
