### ISSUE TITLE
waarschuwing geven bij verwijderen

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#18]
Het is tricky dat wanneer je een bestand verwijdert uit de lijst op http://mi2rdf.netwerkdigitaalerfgoed.nl dat deze dan ook als graph verwijderd wordt op Triply.

We moeten hier op z'n minst een waarschuwing geven of anders misschien ook de vraag stellen of ie op Triply verwijderd moet worden of alleen op mi2rdf...

**Comment by coret** [comment]
Gedrag van verwijder knop nu gewijzigd: alleen de dataset wordt weggehaald, niet de graph in Triply (ook beschreven in tooltip).
