### ISSUE TITLE
Internal Server Error bij verwijderen bestand

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#19]
Bestand lijkt verwijdert te worden maar na een refresh blijkt hij er nog te zijn. Server geeft een error 500
 ![Screenshot 2020-10-28 at 18 58 58](https://user-images.githubusercontent.com/156066/97477318-c3061a80-194f-11eb-997b-2aa21c42df68.JPG)

**Comment by coret** [comment]
Fixed by https://github.com/netwerk-digitaal-erfgoed/mi2rdf/commit/f07269df59d32765e2cbb99507a601f35ad55a98
