### ISSUE TITLE
naamgeving van een graph

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#2]
De graph heeft na het uploaden naar triply standaard een naam zoals `default` of `default-1` etc. Is het mogelijk om de naam van de graph overeen te laten komen met de naam van het ge-uploade tekstbestand?

**Comment by coret** [comment]
Op zich wel. Ik stel voor dat het .txt deel en _MAISI_EXP achterwege kan worden gelaten. Dus dan wordt BEELDBANK_14_131_MAISI_EXP.txt de graph naam BEELDBANK_14_131.

**Comment by coret** [comment]
doorgevoerd https://github.com/netwerk-digitaal-erfgoed/mi2rdf/commit/4d367fb9e9c095e8854660aa384ccee4aaed89c5
