### ISSUE TITLE
probleem bij opslaan Kladblok?

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#20]
Het lijkt er op dat momenteel het kladblok niet bewaard wordt. Er verschijnt geen foutmelding. Bij 'Validate' is de syntax correct maar bij Opslaan verschijnt de oude/vorige tekst weer in het kladblok.

![Screenshot 2020-11-09 at 21 03 59](https://user-images.githubusercontent.com/156066/98590462-250b3c00-22cf-11eb-834b-d33b013ec9ef.JPG)

Na opslaan:
![Screenshot 2020-11-09 at 21 04 09](https://user-images.githubusercontent.com/156066/98590467-276d9600-22cf-11eb-91af-40160339a400.JPG)

**Comment by companje** [comment]
Zou het zo kunnen zijn dat het Kladblok van Het Utrechts Archief niet wordt ingelezen (want die bestond nog niet blijkbaar). Maar nu die wel bestaat wordt alsnog die van het Waterlandsarchief getoond...

**Comment by coret** [comment]
Het validatiecomponent gooide wat roet in het eten, maar oplossing was eenvoudig (en is doorgevoerd).
