### ISSUE TITLE
URI van waterlandsarchief ipv hetutrechtsarchief

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#21]
Base URI bij instellingen staat ingesteld op https://hetutrechtsarchief.nl.nl/id/
Ook in `context.json` staat  
```
     "@base": "https://hetutrechtsarchief.nl/id/",
    "@vocab" : "https://hetutrechtsarchief.nl/def/",
```
Desondanks komt in de graph het volgende terecht: `https://waterlandsarchief.nl/def/aet#thtm`

Zou het kunnen dat er nog ergens anders hardcoded een URI staat? Of wordt de `adt_id` misschien verkeerd aan het `mfxml2jsonld.py` script doorgegeven?

![Screenshot 2020-11-18 at 16 15 00](https://user-images.githubusercontent.com/156066/99548755-464be680-29b9-11eb-9100-36dffe76b33b.JPG)

**Comment by coret** [comment]
https://github.com/netwerk-digitaal-erfgoed/mi2rdf/blob/2a9fc3e4379b719cf860df7b26f769ae7e529edd/consumer/onmessage.sh#L75 en https://github.com/netwerk-digitaal-erfgoed/mi2rdf/blob/2a9fc3e4379b719cf860df7b26f769ae7e529edd/consumer/onmessage.sh#L80  oeps

**Comment by coret** [comment]
In conversie naar triples zie ik:

- "https://waterlandsarchief.nl/"
- "https://waterlandsarchief.nl/def/"
- **"https://waterlandsarchief.nl/id/"**
- "https://waterlandsarchief.nl/def/aet#"

Alleen de vetgedrukte waarde hebben we nu configurabel als **Base URI**. Ga dit uitbreiden in db/gui en dan gebruiken in de conversie.

**Comment by coret** [comment]
opgelost via https://github.com/netwerk-digitaal-erfgoed/mi2rdf/commit/026d0bdbf4b4ce360fe9e2dc2298ec6e5e76a09c#diff-28c83f32ea3ab9694ee9afd7e2ce060bcba5f64d73ef0debe5ac1b49a849165d
