### ISSUE TITLE
upload grote bestanden

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#3]
Is het mogelijk om ondersteuning voor grote bestanden (honderden MB's) te ondersteunen?

```
upload.php: Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```
beeldbank-12-11-2019.txt
filesize: 343MB

**Comment by coret** [comment]
upload is verhoogd naar 500MB (max staat in tooltip bij upload button)

**Comment by companje** [comment]
Volgens mij gaat hier nog iets mis. Ik zie geen progressbar en krijg wel een error in m'n console. Het bestand is 343 MB.

<img width="577" alt="Screenshot 2020-03-31 at 11 19 51" src="https://user-images.githubusercontent.com/156066/78009608-8f273000-7341-11ea-9754-3dbe7cf1a6ce.png">

<img width="1211" alt="Screenshot 2020-03-31 at 11 18 44" src="https://user-images.githubusercontent.com/156066/78009611-8fbfc680-7341-11ea-8d89-0e4607ee83db.png">

**Comment by coret** [comment]
Ah, Nginx had ook een max (had alleen PHP-FPM aangepast), deze heb ik nu ook verhoogd.

**Comment by companje** [comment]
top!
