### ISSUE TITLE
link naar triplestore

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#4]
Zou de link naar de triplestore http://demo.netwerkdigitaalerfgoed.nl/mi2rdf/ getoond kunnen worden? 

https://data.netwerkdigitaalerfgoed.nl/MI2RDF/mi2rdf

**Comment by coret** [comment]
Ja hoor!

**Comment by companje** [comment]
Oeps ik was wat onduidelijk in mijn issue. Dit is de juiste link: https://data.netwerkdigitaalerfgoed.nl/MI2RDF/mi2rdf
