### ISSUE TITLE
iconen verspringen soms naar volgende regel

### ISSUE THREAD

**Issue by companje** [netwerk-digitaal-erfgoed/mi2rdf#9]
iconen verspringen soms naar volgende regel, zie afbeelding:
![Screenshot 2020-05-12 at 14 39 18](https://user-images.githubusercontent.com/156066/81692566-e3ecb900-945e-11ea-82f2-4f791ae52491.JPG)

**Comment by coret** [comment]
Afstand tussen knoppen verkleind via CSS.
